"""Tests for fetch_diff.py — the pure, network-free diff-processing functions."""

from __future__ import annotations

from pathlib import Path

from fetch_diff import (
    extract_stacked_pr_base_sha,
    filter_diff,
    is_autogenerated_file,
)

SIMPLE_DIFF = """diff --git a/file.py b/file.py
index abc1234..def5678 100644
--- a/file.py
+++ b/file.py
@@ -10,3 +10,3 @@
 context line
-old line
+new line
"""

TWO_FILE_DIFF = """diff --git a/keep.py b/keep.py
index aaa..bbb 100644
--- a/keep.py
+++ b/keep.py
@@ -1,1 +1,1 @@
-a
+b
diff --git a/drop.ts b/drop.ts
index ccc..ddd 100644
--- a/drop.ts
+++ b/drop.ts
@@ -1,1 +1,1 @@
-x
+y
"""

MASKED_DIFF = """diff --git a/uv.lock b/uv.lock
index aaa..bbb 100644
--- a/uv.lock
+++ b/uv.lock
@@ -1,2 +1,2 @@
-old pin
+new pin
"""

DELETED_DIFF = """diff --git a/gone.py b/gone.py
deleted file mode 100644
index aaa..0000000 100644
--- a/gone.py
+++ /dev/null
@@ -1,2 +0,0 @@
-line one
-line two
"""

STACKED_BODY = """## Stacked PR

- [branch-a](https://github.com/o/r/pull/1) [Files changed](https://github.com/o/r/pull/1/files)
  - [**feature-b**](https://github.com/o/r/pull/2) \
[Files changed](https://github.com/o/r/pull/2/files/abc1234..def5678)
"""


class TestFilterDiff:
    """Line-number annotation and file filtering."""

    def test_annotates_each_line_kind(self) -> None:
        """Deleted lines get the left number, added the right, context both."""
        out = filter_diff(SIMPLE_DIFF)
        assert "   10    10 |  context line" in out
        assert "   11       | -old line" in out
        assert "         11 | +new line" in out

    def test_preserves_diff_headers(self) -> None:
        """The diff --git and @@ header lines survive annotation untouched."""
        out = filter_diff(SIMPLE_DIFF)
        assert "diff --git a/file.py b/file.py" in out
        assert "@@ -10,3 +10,3 @@" in out

    def test_file_patterns_keep_only_matches(self) -> None:
        """A glob pattern drops non-matching diff --git blocks entirely."""
        out = filter_diff(TWO_FILE_DIFF, file_patterns=["*.py"])
        assert "keep.py" in out
        assert "drop.ts" not in out
        assert "+y" not in out

    def test_blank_line_between_files(self) -> None:
        """A blank line separates consecutive file blocks."""
        out = filter_diff(TWO_FILE_DIFF)
        lines = out.split("\n")
        second = lines.index("diff --git a/drop.ts b/drop.ts")
        assert lines[second - 1] == ""

    def test_empty_diff_returns_empty_string(self) -> None:
        """An empty diff annotates to an empty string, not an error."""
        assert filter_diff("") == ""

    def test_autogenerated_file_is_masked(self) -> None:
        """A lock-file diff is masked and its hunk content suppressed."""
        out = filter_diff(MASKED_DIFF)
        assert "[Auto-generated file - diff masked]" in out
        assert "+new pin" not in out
        assert "--- a/uv.lock" in out

    def test_deleted_file_is_masked(self) -> None:
        """A deleted file shows the deleted-file mask and drops hunk lines."""
        out = filter_diff(DELETED_DIFF)
        assert "[Deleted file - diff masked]" in out
        assert "line one" not in out


class TestIsAutogeneratedFile:
    """Auto-generated-file detection (mlflow/protos branch removed)."""

    def test_lock_files_are_autogenerated(self) -> None:
        assert is_autogenerated_file("uv.lock") is True
        assert is_autogenerated_file("frontend/yarn.lock") is True
        assert is_autogenerated_file("package-lock.json") is True

    def test_ordinary_python_file_is_not(self) -> None:
        assert is_autogenerated_file("src/main.py") is False

    def test_protos_python_path_is_not_masked(self) -> None:
        """The mlflow-specific mlflow/protos branch is gone — such files are kept."""
        assert is_autogenerated_file("foo/protos/service_pb2.py") is False

    def test_generated_java_header_detected(self, tmp_path: Path) -> None:
        """A .java file with the protobuf header is auto-generated."""
        java = tmp_path / "Generated.java"
        java.write_text("// Generated by the protocol buffer compiler. DO NOT EDIT!\n")
        assert is_autogenerated_file(str(java)) is True

    def test_handwritten_java_is_not(self, tmp_path: Path) -> None:
        java = tmp_path / "Hand.java"
        java.write_text("package com.example;\n")
        assert is_autogenerated_file(str(java)) is False


class TestExtractStackedPrBaseSha:
    """Stacked-PR base-SHA extraction (an mlflow-flavored convention)."""

    def test_returns_base_sha_for_bold_branch(self) -> None:
        assert extract_stacked_pr_base_sha(STACKED_BODY, "feature-b") == "abc1234"

    def test_returns_none_without_stacked_marker(self) -> None:
        assert extract_stacked_pr_base_sha("Just an ordinary PR body.", "feature-b") is None

    def test_returns_none_for_none_body(self) -> None:
        assert extract_stacked_pr_base_sha(None, "feature-b") is None

    def test_returns_none_when_branch_not_in_stack(self) -> None:
        assert extract_stacked_pr_base_sha(STACKED_BODY, "other-branch") is None
