"""Tests for fetch_diff.py — the pure, network-free diff-processing functions.

Pure helpers are imported directly (see conftest.py sys.path shim). The local
``--base`` mode is exercised against a real throwaway git repo, since its whole
job is to shell out to git.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from fetch_diff import (
    extract_stacked_pr_base_sha,
    fetch_local_diff,
    filter_diff,
    is_autogenerated_file,
    is_migration_path,
)

SIMPLE_DIFF = """diff --git a/file.py b/file.py
index abc1234..def5678 100644
--- a/file.py
+++ b/file.py
@@ -10,3 +10,3 @@
 context line
-old line
+new line
"""

TWO_FILE_DIFF = """diff --git a/keep.py b/keep.py
index aaa..bbb 100644
--- a/keep.py
+++ b/keep.py
@@ -1,1 +1,1 @@
-a
+b
diff --git a/drop.ts b/drop.ts
index ccc..ddd 100644
--- a/drop.ts
+++ b/drop.ts
@@ -1,1 +1,1 @@
-x
+y
"""

MASKED_DIFF = """diff --git a/uv.lock b/uv.lock
index aaa..bbb 100644
--- a/uv.lock
+++ b/uv.lock
@@ -1,2 +1,2 @@
-old pin
+new pin
"""

DELETED_DIFF = """diff --git a/gone.py b/gone.py
deleted file mode 100644
index aaa..0000000 100644
--- a/gone.py
+++ /dev/null
@@ -1,2 +0,0 @@
-line one
-line two
"""

MIGRATION_DIFF = """diff --git a/db/migrations/0002_drop.py b/db/migrations/0002_drop.py
index aaa..bbb 100644
--- a/db/migrations/0002_drop.py
+++ b/db/migrations/0002_drop.py
@@ -1,2 +1,3 @@
 def upgrade():
+    op.drop_column('users', 'email')
     pass
"""

STACKED_BODY = """## Stacked PR

- [branch-a](https://github.com/o/r/pull/1) [Files changed](https://github.com/o/r/pull/1/files)
  - [**feature-b**](https://github.com/o/r/pull/2) \
[Files changed](https://github.com/o/r/pull/2/files/abc1234..def5678)
"""


class TestFilterDiff:
    """Line-number annotation and file filtering."""

    def test_annotates_each_line_kind(self) -> None:
        """Deleted lines get the left number, added the right, context both."""
        out = filter_diff(SIMPLE_DIFF)
        assert "   10    10 |  context line" in out
        assert "   11       | -old line" in out
        assert "         11 | +new line" in out

    def test_preserves_diff_headers(self) -> None:
        """The diff --git and @@ header lines survive annotation untouched."""
        out = filter_diff(SIMPLE_DIFF)
        assert "diff --git a/file.py b/file.py" in out
        assert "@@ -10,3 +10,3 @@" in out

    def test_file_patterns_keep_only_matches(self) -> None:
        """A glob pattern drops non-matching diff --git blocks entirely."""
        out = filter_diff(TWO_FILE_DIFF, file_patterns=["*.py"])
        assert "keep.py" in out
        assert "drop.ts" not in out
        assert "+y" not in out

    def test_blank_line_between_files(self) -> None:
        """A blank line separates consecutive file blocks."""
        out = filter_diff(TWO_FILE_DIFF)
        lines = out.split("\n")
        second = lines.index("diff --git a/drop.ts b/drop.ts")
        assert lines[second - 1] == ""

    def test_empty_diff_returns_empty_string(self) -> None:
        """An empty diff annotates to an empty string, not an error."""
        assert filter_diff("") == ""

    def test_trailing_newline_does_not_invent_an_anchor(self) -> None:
        """A diff's trailing newline must not become a phantom annotated line.

        Real diffs end with a newline, so a naive split() leaves a trailing "" that
        annotates as a context line — inventing a line number one past the end of the
        hunk. Downstream that is a valid-looking anchor for a comment on a line that
        does not exist.
        """
        assert SIMPLE_DIFF.endswith("\n")
        out = filter_diff(SIMPLE_DIFF)
        last = out.split("\n")[-1]
        assert last.strip(), f"trailing blank annotated line: {last!r}"
        # SIMPLE_DIFF's hunk ends at new line 12; nothing may be annotated past it.
        assert "   13" not in out
        assert out.endswith("+new line")

    def test_autogenerated_file_is_masked(self) -> None:
        """A lock-file diff is masked and its hunk content suppressed."""
        out = filter_diff(MASKED_DIFF)
        assert "[Auto-generated file - diff masked]" in out
        assert "+new pin" not in out
        assert "--- a/uv.lock" in out

    def test_deleted_file_is_masked(self) -> None:
        """A deleted file shows the deleted-file mask and drops hunk lines."""
        out = filter_diff(DELETED_DIFF)
        assert "[Deleted file - diff masked]" in out
        assert "line one" not in out


class TestIsAutogeneratedFile:
    """Auto-generated-file detection (mlflow/protos branch removed)."""

    def test_lock_files_are_autogenerated(self) -> None:
        assert is_autogenerated_file("uv.lock") is True
        assert is_autogenerated_file("frontend/yarn.lock") is True
        assert is_autogenerated_file("package-lock.json") is True

    @pytest.mark.parametrize(
        "lock",
        ["bun.lock", "bun.lockb", "Cargo.lock", "go.sum", "pnpm-lock.yaml", "poetry.lock", "Gemfile.lock"],
    )
    def test_widened_lock_file_set(self, lock: str) -> None:
        """The filter covers the wider ecosystem, not just uv/yarn/npm."""
        assert is_autogenerated_file(f"sub/dir/{lock}") is True

    @pytest.mark.parametrize("name", ["app.min.js", "theme.min.css", "bundle.js.map"])
    def test_minified_and_sourcemaps_are_masked(self, name: str) -> None:
        assert is_autogenerated_file(f"static/{name}") is True

    def test_generated_marker_in_first_line(self, tmp_path: Path) -> None:
        """A first-line @generated marker masks the file regardless of suffix."""
        gen = tmp_path / "schema.ts"
        gen.write_text("// @generated by codegen — do not edit\nexport const x = 1;\n")
        assert is_autogenerated_file(str(gen)) is True

    def test_ordinary_python_file_is_not(self) -> None:
        assert is_autogenerated_file("src/main.py") is False


class TestMigrationsAreExempt:
    """Migrations must always reach a reviewer — a bad one can destroy prod data."""

    def test_migration_path_detected(self) -> None:
        assert is_migration_path("db/migrations/0001_init.py") is True
        assert is_migration_path("src/main.py") is False

    def test_migration_is_never_masked_even_when_lock_named(self, tmp_path: Path) -> None:
        """The exemption beats every other rule, including the generated marker."""
        mig = tmp_path / "migrations" / "0002_add_column.py"
        mig.parent.mkdir()
        mig.write_text("# @generated by alembic\nrevision = '0002'\n")
        assert is_autogenerated_file(str(mig)) is False

    def test_migration_hunks_survive_filter_diff(self) -> None:
        """End-to-end: a migration's content is annotated, not masked."""
        out = filter_diff(MIGRATION_DIFF)
        assert "[Auto-generated file - diff masked]" not in out
        assert "+    op.drop_column('users', 'email')" in out

    def test_protos_python_path_is_not_masked(self) -> None:
        """The mlflow-specific mlflow/protos branch is gone — such files are kept."""
        assert is_autogenerated_file("foo/protos/service_pb2.py") is False

    def test_generated_java_header_detected(self, tmp_path: Path) -> None:
        """A .java file with the protobuf header is auto-generated."""
        java = tmp_path / "Generated.java"
        java.write_text("// Generated by the protocol buffer compiler. DO NOT EDIT!\n")
        assert is_autogenerated_file(str(java)) is True

    def test_handwritten_java_is_not(self, tmp_path: Path) -> None:
        java = tmp_path / "Hand.java"
        java.write_text("package com.example;\n")
        assert is_autogenerated_file(str(java)) is False


class TestExtractStackedPrBaseSha:
    """Stacked-PR base-SHA extraction (an mlflow-flavored convention)."""

    def test_returns_base_sha_for_bold_branch(self) -> None:
        assert extract_stacked_pr_base_sha(STACKED_BODY, "feature-b") == "abc1234"

    def test_returns_none_without_stacked_marker(self) -> None:
        assert extract_stacked_pr_base_sha("Just an ordinary PR body.", "feature-b") is None

    def test_returns_none_for_none_body(self) -> None:
        assert extract_stacked_pr_base_sha(None, "feature-b") is None

    def test_returns_none_when_branch_not_in_stack(self) -> None:
        assert extract_stacked_pr_base_sha(STACKED_BODY, "other-branch") is None


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True)


@pytest.fixture
def branched_repo(tmp_path: Path) -> Path:
    """A git repo on a feature branch, one commit ahead of main."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-b", "main")
    _git(repo, "config", "user.email", "t@t.test")
    _git(repo, "config", "user.name", "Test")

    (repo / "app.py").write_text("def add(a, b):\n    return a + b\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "base")

    _git(repo, "checkout", "-b", "feature")
    (repo / "app.py").write_text("def add(a, b):\n    return a - b\n")
    (repo / "uv.lock").write_text("pinned = 1\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-m", "change")
    return repo


class TestFetchLocalDiff:
    """Local --base mode: the same annotator, sourced from git instead of GitHub."""

    def test_annotates_local_branch_diff(self, branched_repo: Path) -> None:
        """A local merge-base diff comes back annotated exactly like a PR diff."""
        out = fetch_local_diff("main", cwd=branched_repo)
        assert "diff --git a/app.py b/app.py" in out
        # Added lines carry the new-file number on the right, deleted the old on the left.
        assert "          2 | +    return a - b" in out
        assert "    2       | -    return a + b" in out

    def test_noise_filter_applies_in_local_mode(self, branched_repo: Path) -> None:
        """Lock files are masked on the local path too, not just the PR path."""
        out = fetch_local_diff("main", cwd=branched_repo)
        assert "[Auto-generated file - diff masked]" in out
        assert "pinned = 1" not in out

    def test_file_patterns_apply_in_local_mode(self, branched_repo: Path) -> None:
        out = fetch_local_diff("main", file_patterns=["*.py"], cwd=branched_repo)
        assert "app.py" in out
        assert "uv.lock" not in out

    def test_unknown_ref_raises_value_error(self, branched_repo: Path) -> None:
        with pytest.raises(ValueError, match="failed"):
            fetch_local_diff("no-such-ref", cwd=branched_repo)
