"""Regression tests for scripts/validate-unicode-hygiene.py.

The validator is invoked as a CLI via subprocess (valid because the script is
stdlib-only) so the assertions cover real exit codes, per-severity counts, and
flag behaviour end-to-end. Fixtures are byte-precise and generated by
tests/fixtures/unicode-hygiene/_generate.py.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "scripts" / "validate-unicode-hygiene.py"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "unicode-hygiene"


def run(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True,
        text=True,
        check=False,
    )


def run_fixture(name: str, *flags: str) -> subprocess.CompletedProcess[str]:
    return run(*flags, str(FIXTURES / name))


def test_clean_fixture_has_no_findings() -> None:
    result = run_fixture("clean-skill.md")
    assert result.returncode == 0
    assert "0 BLOCKER, 0 MAJOR, 0 MINOR" in result.stdout


def test_leading_bom_is_allowed() -> None:
    result = run_fixture("bom-allowed.md")
    assert result.returncode == 0
    assert "0 BLOCKER, 0 MAJOR, 0 MINOR" in result.stdout


def test_tag_characters_are_blocker() -> None:
    result = run_fixture("blocker-tag-chars.md")
    assert result.returncode == 1
    assert "BLOCKER tag-character" in result.stdout
    assert "U+E0061" in result.stdout


def test_bidi_override_is_blocker() -> None:
    result = run_fixture("blocker-bidi-override.md")
    assert result.returncode == 1
    assert "BLOCKER bidi-control" in result.stdout
    assert "U+202E" in result.stdout


def test_zero_width_is_major_and_passes_by_default() -> None:
    result = run_fixture("major-zero-width.md")
    assert result.returncode == 0
    assert "MAJOR zero-width-or-format" in result.stdout
    assert "0 BLOCKER, 1 MAJOR, 0 MINOR" in result.stdout


def test_zero_width_fails_under_strict() -> None:
    result = run_fixture("major-zero-width.md", "--strict")
    assert result.returncode == 1
    assert "MAJOR zero-width-or-format" in result.stdout


def test_homoglyph_is_minor() -> None:
    result = run_fixture("minor-homoglyph-install.md")
    assert result.returncode == 0
    assert "MINOR mixed-script-identifier" in result.stdout
    assert "0 BLOCKER, 0 MAJOR, 1 MINOR" in result.stdout


def test_warn_only_always_exits_zero() -> None:
    result = run_fixture("blocker-tag-chars.md", "--warn-only")
    assert result.returncode == 0
    assert "BLOCKER tag-character" in result.stdout


def test_default_full_repo_scan_is_clean() -> None:
    # No arguments -> default target globs over the real repo. The malicious
    # fixtures are deliberately NOT in DEFAULT_TARGETS, so this must pass.
    result = run()
    assert result.returncode == 0, result.stdout
    assert "blocker-tag-chars.md" not in result.stdout
    assert "0 BLOCKER" in result.stdout
